server:
  port: ${PORT}

spring:
  application:
    name: spring-examples
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maxActive: 3
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
      format_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    locations: classpath:db/migrations

kafka:
  enabled: true
  producer:
    bootstrap-server: ${KAFKA_PRODUCER_BOOTSTRAP_SERVER}
  consumer:
    bootstrap-server: ${KAFKA_CONSUMER_BOOTSTRAP_SERVER}
    group-id: ${KAFKA_CONSUMER_GROUP_ID}
  topics:
      any-topic: any-topic
